### PR TITLE
fix sql, bq, storage location exemptions empty list

### PR DESCRIPTION
**Pull request by xingao267**
Fixes https://github.com/forseti-security/policy-library/issues/369

### CODE REVIEW

**Comment by xingao267** [comment]
Seems like there are test cases for exemption
https://github.com/forseti-security/policy-library/tree/master/validator/test/fixtures/sql_location/constraints
https://github.com/forseti-security/policy-library/tree/master/validator/test/fixtures/storage_location/constraints
https://github.com/forseti-security/policy-library/tree/master/validator/test/fixtures/bq_dataset_location/constraints

**Comment by morgante** [comment]
None of the existing test cases test what happens when `exemptions` isn't specified at all. I recommend we add a test case to avoid regression.

**Comment by xingao267** [comment]
@morgante I modified the allowlist_one test case to not specify the exemptions_list to prevent regression. The empty exemptions_list being specified case is still tested in the allowlist_all case.

**Comment by morgante** [comment]
Perfect, thanks!

**Pull request merged**
