### PR TITLE
Add more CMEK settings

### PR DESCRIPTION
**Pull request by charliewolf**

### CODE REVIEW

**Comment by charliewolf** [comment]
@morgante i think @joecheuk had requested i make it part of the same one, and that's the approach that made most sense to me as well, but i'm open to splitting it out

**Comment by joecheuk** [comment]
There might be some miscommunication but the decision we made was to create a separate one for the new use cases.

**Comment by AdrienWalkowiak** [comment]
Looks like there are conflicts to resolve on this one.

**Comment by AdrienWalkowiak** [comment]
If we are going for a separate constraint then no need to solve the conflict - just close this PR.

**Comment by ocervell** [comment]
What's the rationale for creating a separate rule here ?

**Comment by charliewolf** [comment]
@AdrienWalkowiak  @morgante @joecheuk it is now a separate policy

**Comment by charliewolf** [comment]
@AdrienWalkowiak why did you close this?

**Comment by AdrienWalkowiak** [comment]
I thought you would open a new PR for the new policy and leave this one as-is. Sorry about that.

**Comment by joecheuk** [comment]
@morgante this is now a new template, PTAL

**Pull request merged**
