### PR TITLE
Update constraint files

### PR DESCRIPTION
**Pull request by t12g**
Remove `gcp:` wrapper field for files under `/samples'.
Remove the matcher altogether for test fixture files.

### CODE REVIEW

**Comment by joecheuk** [comment]
Does this break the old FCV instance?

**Comment by t12g** [comment]
@joecheuk the changes under `/samples` will not work with old fcv instance. Is that a concern?

**Comment by joecheuk** [comment]
Is it possible to make the FCV instance backward compatible? We have been advertising to users to sync their repos w/ the policy-libray repos and if they are already using some policies from the policy-library, updating to new FCV version will break all their existing constraints & pulling the changes down from the policy-library break all their current settings if they don't have their FCV updated. We should define the support policy so users can expect how many versions we support for backward compatibility vs releasing breaking changes without letting the users know.

**Comment by t12g** [comment]
So the FCV instance is backwards compatible. Updating FCV will not break existing constraints, as it understands both formats (with and without the `gcp` wrapper field). 

What's incompatible in this PR is that an old FCV instance will ignore the matchers defined in the sample constraints. However, they're all "match all" anyways (the default behavior). Does that address your concern? Alternatively, we could also remove the `match` block everywhere. WDYT?

**Comment by joecheuk** [comment]
Got it, thanks for the clarifications!

**Pull request merged**
